Initial Import of Historical Data
DarwinsBuddy/WienerNetzeSmartmeter pull request #101
Opened 2023-04-08 16:14 UTC by reox

yet another thing to test ;)

Implemented the fetching of the historical data and import it on initial sensor setup.

This resolves #26 - at least partially, because it grabs the data directly instead of asking

2023-04-08 16:33 UTC, reox commented
@DarwinsBuddy I do not understand why the tests are failing here. The response should be mocked including the expire times, and thus also on calling `login()` also the expire variables should be set - no?

2023-04-08 19:59 UTC, DarwinsBuddy commented
> @DarwinsBuddy I do not understand why the tests are failing here. The response should be mocked including the expire times, and thus also on calling `login()` also the expire variables should be set - no?

My bad. I made a mistake setting up that test case

2023-04-08 20:34 UTC, DarwinsBuddy commented
I launched it, got a warning stating that the updating of the sensor took > 10 seconds. Maybe 3 years is a bit far in the past for one shot.

Afterwards I was not able to see any historical data in the sensor. Where should I be able to see the pulled data?

2023-04-08 20:45 UTC, DarwinsBuddy requested changes
Please run

`flake8 custom_components/wnsm --count --select=E9,F63,F7,F82 --show-source --statistics --config tests/setup.cfg`
and
`flake8 custom_components/wnsm --count --exit-zero --max-complexity=10 --statistics --config tests/setup.cfg`

and resolve the issues. (sometimes it pays of to disable them inline ` #noqa: XXX`

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            raise SmartmeterConnectionError(f'Bearer token required, but got {res_json["token_type"]!r}')
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            raise SmartmeterConnectionError("Access Token is not valid anymore, please re-log!")
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            raise SmartmeterConnectionError("Access Token is not valid anymore, please re-log!")
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            headers['X-Gateway-APIKey'] = self._api_gateway_b2b_token
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            headers.update(extra_headers)
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            logger.debug("DATA: %s" % data)
Please add a test for this
Reconsider logging of this data

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        return self.verbrauch(day.replace(hour=0, minute=0, second=0, microsecond=0), zaehlpunkt, resolution)
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            zaehlpunkt = self._get_first_zaehlpunkt()
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            date_until = date.today()
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            date_from  = date_until.replace(year=date_until.year - 3)
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        query = {
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        extra = {
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        data = self._call_api('zaehlpunkte/messwerte', base_url=const.API_URL_B2B, query=query, extra_headers=extra)
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        obis_code = data[0]['zaehlwerke'][0]['obisCode']
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            logger.warning(f"The OBIS code of the meter ({obis_code}) reports that this meter does not count electrical energy!")
Please add a test for this

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        logger.debug(f"LOGIN RESULT: {result.json()}")
Commits introducing logging of sensitive data (even if it's debug) is maybe not a good idea

2023-04-08 20:45 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        logger.debug("LOGIN HEADERS: %s" % result.headers)
Commits introducing logging of sensitive data (even if it's debug) is maybe not a good idea

2023-04-09 08:18 UTC, reox commented
> That is amazing! How did you find out this is a feature of the b2b api?

just watched the webpage with the developer tools :grinning: 

> Maybe 3 years is a bit far in the past for one shot.

When you visit the dataexport in the smartmeter-web, 3 years is the standard setting. Thus I thought it might be OK to do the same. Does it take very long for you? I only have smartmeter entries since November 2023, and thus with any date range it is actually quite fast.

I just thought about an issue with this approach: If for some reason it fails to gather the data, the init procedure will be called again and again. So we need some way of determining that the init was called once and do not start it again.

2023-04-09 08:19 UTC, reox commented on custom_components/wnsm/api/client.py
> +        logger.debug("LOGIN HEADERS: %s" % result.headers)
Ah yes, that is true. I'll remove them!

2023-04-09 08:24 UTC, reox commented on custom_components/wnsm/api/client.py
> +            logger.debug("DATA: %s" % data)
this data thing is actually from the original API. It is only used for the `user/ereignis` endpoint - which I never used.

2023-04-09 11:14 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> -import pprint
thanks :grimacing: I forgot this

2023-04-09 11:21 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            logger.debug("DATA: %s" % data)
ah I see. then let's remove this for good. the less individual user data logging, the better.

2023-04-09 11:25 UTC, DarwinsBuddy commented
> > That is amazing! How did you find out this is a feature of the b2b api?
> 
> just watched the webpage with the developer tools grinning
> 
So same technique as I did it. :) but I've not discovered this part yet. Good catch! :heart: 

> > Maybe 3 years is a bit far in the past for one shot.
> 
> When you visit the dataexport in the smartmeter-web, 3 years is the standard setting. Thus I thought it might be OK to do the same. Does it take very long for you? I only have smartmeter entries since November 2023, and thus with any date range it is actually quite fast.
> 
> I just thought about an issue with this approach: If for some reason it fails to gather the data, the init procedure will be called again and again. So we need some way of determining that the init was called once and do not start it again.


hmm... I guess then 3years should be fine. But you have a point there. What we could do though is only try it once at set-up. If it fails we shouldn't trigger it anew. We can implement an option in the config_flow to trigger it manually. I have to look into the details though. so better add an `at most once` logic, create another issue and let's solve this after this monster of a branch is in `main` :smiley:

2023-04-10 08:47 UTC, reox commented on custom_components/wnsm/api/client.py
> +        return self.verbrauch(day.replace(hour=0, minute=0, second=0, microsecond=0), zaehlpunkt, resolution)
This function is only ever used in `live_sensor` as a fallback. The question here is what this function now actually queries. It correctly sets the day to 00:00:00 UTC - but does not check if a timezone is set in the datetime. However, probably what should be done here is to set it to 00:00:00 Local time, i.e. probably CE(S)T.

2023-04-10 11:32 UTC, reox commented on custom_components/wnsm/api/client.py
> +            logger.warning(f"The OBIS code of the meter ({obis_code}) reports that this meter does not count electrical energy!")
it would be interesting to know how the data looks like for others... All these checks were just assumptions I made by looking at my own data. But I only have one zählpunkt and not the longest coverage of values.
Thus, it is a bit hard to test right now :sweat_smile:

2023-04-16 16:13 UTC, DarwinsBuddy commented
@reox unless you have any concerns. I'd release this feature. It's downwards compatible and runs smoothly already.

Regarding 
 
> > When you visit the dataexport in the smartmeter-web, 3 years is the standard setting. Thus I thought it might be OK to do the same. Does it take very long for you? I only have smartmeter entries since November 2023, and thus with any date range it is actually quite fast.
> > I just thought about an issue with this approach: If for some reason it fails to gather the data, the init procedure will be called again and again. So we need some way of determining that the init was called once and do not start it again.
> 
> hmm... I guess then 3years should be fine. But you have a point there. What we could do though is only try it once at set-up. If it fails we shouldn't trigger it anew. We can implement an option in the config_flow to trigger it manually. I have to look into the details though. so better add an `at most once` logic, create another issue and let's solve this after this monster of a branch is in `main` smiley

I'd create another issue, when I've got your Okay. :)

2023-04-16 16:35 UTC, reox commented
@DarwinsBuddy  it runs also smoothly on my side! Except some missing test cases, I think it is good to go :)

2023-04-23 10:18 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            headers['X-Gateway-APIKey'] = self._api_gateway_b2b_token
see #113

2023-04-23 10:18 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            headers.update(extra_headers)
see #113

2023-04-23 10:19 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        return self.verbrauch(day.replace(hour=0, minute=0, second=0, microsecond=0), zaehlpunkt, resolution)
I guess the WienerNetzeAPI is not caring for timezones, thus it's assuming Europe/Vienna as the default timezone when submitting UTC. But that's just a wild guess.

Also see  #113

2023-04-23 10:19 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            zaehlpunkt = self._get_first_zaehlpunkt()
see #113

2023-04-23 10:19 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            date_until = date.today()
see #113

2023-04-23 10:19 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            date_from  = date_until.replace(year=date_until.year - 3)
see #113

2023-04-23 10:19 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        query = {
see #113

2023-04-23 10:19 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        extra = {
see #113

2023-04-23 10:19 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +        data = self._call_api('zaehlpunkte/messwerte', base_url=const.API_URL_B2B, query=query, extra_headers=extra)
see #113

2023-04-23 10:20 UTC, DarwinsBuddy commented on custom_components/wnsm/api/client.py
> +            logger.warning(f"The OBIS code of the meter ({obis_code}) reports that this meter does not count electrical energy!")
see #113

2023-04-23 10:23 UTC, DarwinsBuddy approved these changes
lgtm

2023-04-23 10:24 UTC, merged