Check if historical data was returned
DarwinsBuddy/WienerNetzeSmartmeter pull request #144
Opened 2023-05-22 08:11 UTC by reox

resolves #143

There is just one question now: In this case, the historical data import will be triggered every time until there is any data.
@DarwinsBuddy Should we write an empty statistics here to prevent the import the next time?

2023-05-22 08:19 UTC, DarwinsBuddy commented
Empty one might be the safe call. Only prerequisite for it should be that we definitely know that there is no data to import, and it's not a flaky response

2023-05-22 09:00 UTC, reox commented
>  Only prerequisite for it should be that we definitely know that there is no data to import, and it's not a flaky response

I guess this is very hard to test... Or can we maybe query somehow when the smartmeter was activated? Then it would be relatively easy to decide if there is data to be expected.

2023-07-04 08:26 UTC, flo071 requested changes
Works like a charm, when it comes to the point that there are no errors thrown anymore, but we do not get the info, change it to `_LOGGER.debug("")` and it would be fine.

2023-08-31 20:14 UTC, DarwinsBuddy approved these changes
lgtm

2023-08-31 20:15 UTC, merged