Fix consumption update for live sensor of second zaehlpunkt
DarwinsBuddy/WienerNetzeSmartmeter pull request #233
Opened 2024-05-21 19:36 UTC by tschoerk

When updating the consumption data for the second zaehlerpunkt, the base meter readings don't have the information for this zaehlerpunkt, since it's not the "default" zaehlerpunkt. So the live sensor tries to get the information by checking the consumption data for yesterday to update the sensor with this value. This second method has several bugs though, which this pull request aims to fix.

This should resolve #227

2024-08-06 07:57 UTC, tschoerk commented
Both live sensors receive the meter readings the same way now by calling the historical data API with the value type METER_READ which returns the meter reading for each day. The latest value is then used to update the live sensor. This can be done with one or more zaehlpunkte and all return the same value type now, which is the total usage/feeding since implementation of the zaehlpunkt. This fixes the problems with the live sensor on a second zaehlpunkt as well as makes the output uniform.

2024-09-20 10:21 UTC, DarwinsBuddy requested changes

2024-09-20 10:21 UTC, DarwinsBuddy commented on custom_components/wnsm/base_sensor.py
> -        return translate_dict(response, ATTRS_VERBRAUCH_CALL)
why do we stop translating the response here?

2024-09-20 10:21 UTC, DarwinsBuddy commented on custom_components/wnsm/live_sensor.py
> +                    if "values" in meter_readings and len(meter_readings['values'])!=0:
please format appropriately and use `len(meter_readings['values'] > 0` (negative length arrays are :unicorn: )

maybe a check for `messwert` being present is a good call here

2024-09-20 12:36 UTC, tschoerk commented on custom_components/wnsm/base_sensor.py
> -        return translate_dict(response, ATTRS_VERBRAUCH_CALL)
Beause the original call from the live senser was safeget(verbrauch_raw, [["statistics"], ["average"]]), which called for the untranslated attributes. Since this call is completly gone anyway, this change can be reverted. In hindsight I should have changed the safeget call to call for the correct attributes ("statistics" and "consumptionAverage") , instead of removing the translation.

2024-09-27 10:35 UTC, DarwinsBuddy requested changes
could you rebase onto master?
This project follows the pattern of a linear history. :upside_down_face:

2024-09-27 10:35 UTC, DarwinsBuddy commented on custom_components/wnsm/live_sensor.py
> +            _LOGGER.warning(
are these line breaks coming from your setup, or is this a too strict reformatting config?

2024-09-27 10:35 UTC, DarwinsBuddy commented on custom_components/wnsm/live_sensor.py
>                          _LOGGER.error(
are these line breaks coming from your setup, or is this a too strict reformatting config?

2024-09-27 10:35 UTC, DarwinsBuddy commented on tests/it/test_api.py
> +    expect_history(requests_mock, customer_id, enabled(zaehlpunkt())['zaehlpunktnummer'])
are these line breaks coming from your setup, or is this a too strict reformatting config?

2024-10-01 10:25 UTC, tschoerk commented on custom_components/wnsm/live_sensor.py
> +            _LOGGER.warning(
Which line breaks do you mean? I tried to kept the formatting mostly as it was before, let me know if I missed something. So in this case the multiline warning was kept in the same style as before.

2024-10-01 10:25 UTC, tschoerk commented on custom_components/wnsm/live_sensor.py
>                          _LOGGER.error(
Same as above

2024-10-01 10:26 UTC, tschoerk commented on tests/it/test_api.py
> +    expect_history(requests_mock, customer_id, enabled(zaehlpunkt())['zaehlpunktnummer'])
Which line breaks do you mean here? I have some auto formatting in my setup, but it's fairly limited.

2024-10-04 12:03 UTC, DarwinsBuddy commented
@tschoerk I fear you've created another merge commit instead of rebasing the branch onto master. :grimacing:

2024-10-04 15:06 UTC, tschoerk commented
> @tschoerk I fear you've created another merge commit instead of rebasing the branch onto master. 😬

Sorry not too experienced with git. What to do, to fix this?

2024-10-04 19:38 UTC, DarwinsBuddy commented
1. `git checkout DarwinsBuddy main`
2. `git pull`
3 `git checkout tschoerk bugfix/loadConsumption`
4. `git rebase --onto main`
5. resolve all conflicts one commit at a time by
5.1. resolving
5.2. `git rebase --continue`
5.3. repeat 5.1. until all conflicts are resolved
6. `git push --force-with-lease`

!Be careful! Do point 6 after you've successfully confirmed, that this branch is working as you'd expect it, otherwise throw away the branch, check it out anew and rebase again.

This should resolve all conflicts and remove all merge commits that you've introduced

2024-10-06 19:20 UTC, s00500 commented
Just tested this PR and it seems to work! I was bothered by this issue forever now... 😅

2024-10-07 08:01 UTC, closed without merging

2024-10-07 08:12 UTC, tschoerk commented
Sorry, I probably did something wrong here. I rebased following your instructions and now all my commits in my branch are gone and it's just like main. I will create a new branch with the changes, just so it's kept for future reference. Let me know how to best proceed. Sorry for the inconvenience.

2024-10-07 09:06 UTC, DarwinsBuddy commented
@tschoerk no worries. when I did my first rebase I also messed it up. :) So that's part of the journey

Maybe something that helps
https://saraford.net/2017/04/21/how-to-visualize-a-rebase-in-the-git-visualization-tool-111/

Just file a new PR with the changes applied. :)

2024-10-07 09:11 UTC, s00500 commented
The Rebase tools in VSCode are usually very good :-) (by now it will automatically allow you to continue and understand you are in a rebase)

I usually tell all devs on my team to use autorebase+autostash on pull, once you get comfortable with it it is a great workflow ;-)
On 7. Oct 2024 at 11:06 +0200, Christoph Spörk ***@***.***>, wrote:
> @tschoerk no worries. when I did my first rebase I also messed it up. :) So that's part of the journey
> Maybe something that helps
> https://saraford.net/2017/04/21/how-to-visualize-a-rebase-in-the-git-visualization-tool-111/
> Just file a new PR with the changes applied. :)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>