Bugfix/multiple zps config yaml
DarwinsBuddy/WienerNetzeSmartmeter pull request #261
Opened 2024-09-20 08:56 UTC by DarwinsBuddy

2024-09-20 14:05 UTC, tschoerk commented on custom_components/wnsm/api/client.py
This is from PR #262, should probably be removed from this PR.

2024-09-20 14:05 UTC, tschoerk commented on custom_components/wnsm/base_sensor.py
This is from PR #262, should probably be removed from this PR.

2024-09-20 14:05 UTC, tschoerk commented on custom_components/wnsm/config_flow.py
This is from PR #262, should probably be removed from this PR.

2024-09-20 14:05 UTC, tschoerk commented on custom_components/wnsm/sensor.py
Elegant solution, but I get the following error when trying to install it via configuration.yaml. Something with the way homeassistant handles the configuration. I don't know too much about this, maybe we can figure it out.

`Invalid config for 'sensor' from integration 'wnsm' at configuration.yaml, line 28: value should be a string for dictionary value 'device_id', got ['AT0010000000000000001000000000001', 'AT0010000000000000001000000000002', 'AT0010000000000000001000000000003'], please check the docs at https://github.com/DarwinsBuddy/WienerNetzeSmartmeter`

2024-09-20 14:06 UTC, tschoerk commented on example/secrets.yaml
> +  - AT0010000000000000001000000000003
Elegant solution, but I get the following error when trying to install it via configuration.yaml. Something with the way homeassistant handles the configuration. I don't know too much about this, maybe we can figure it out.

`Invalid config for 'sensor' from integration 'wnsm' at configuration.yaml, line 28: value should be a string for dictionary value 'device_id', got ['AT0010000000000000001000000000001', 'AT0010000000000000001000000000002', 'AT0010000000000000001000000000003'], please check the docs at https://github.com/DarwinsBuddy/WienerNetzeSmartmeter`

2024-09-20 14:07 UTC, tschoerk requested changes

2024-09-20 14:07 UTC, tschoerk commented on example/secrets.yaml
> +  - AT0010000000000000001000000000003
Elegant solution, but I get the following error when trying to install it via configuration.yaml. Something with the way homeassistant handles the configuration. I don't know too much about this, maybe we can figure it out.

`Invalid config for 'sensor' from integration 'wnsm' at configuration.yaml, line 28: value should be a string for dictionary value 'device_id', got ['AT0010000000000000001000000000001', 'AT0010000000000000001000000000002', 'AT0010000000000000001000000000003'], please check the docs at https://github.com/DarwinsBuddy/WienerNetzeSmartmeter`

2024-09-27 10:17 UTC, DarwinsBuddy commented
while going over the config section, I was questioning the approach in general. wouldn't the example provided solve the issue already?

@tschoerk no worries, I've got a backup of your branch as well (additionally to your fork)

2024-10-01 10:16 UTC, tschoerk approved these changes
Yeah that way works perfectly and is much simpler than the solutions before. Good one!

2024-10-04 11:30 UTC, merged