Clean-up and release integration.
DarwinsBuddy/WienerNetzeSmartmeter pull request #31
Opened 2022-12-13 19:52 UTC by TheRealVira

Taking inspiration of https://github.com/vigonotion/hass-simpleicons/tree/master this will help with releases and code clean-ups. Ref. https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues/27

2022-12-14 11:55 UTC, TheRealVira commented
Didn't see it first, but this would also include part of https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/pull/14

2022-12-17 12:21 UTC, DarwinsBuddy requested changes
Wow, you're a beast.
I created that ticket last week and 4 days later we got a cleanup and a release process.
Impressive!

If you could do one more thing?
I read that workflow and like the idea of separating you did. 

Could you document this approach with some instructions how to run the devcontainer etc. in a separate CONTRIBUTING.md (like here https://github.com/redhat-developer/vscode-yaml/blob/main/CONTRIBUTING.md) besides the README.md and refer to it there?

2022-12-17 12:21 UTC, DarwinsBuddy commented on .vscode/launch.json
> +    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
please do not commit comments in json :)

2022-12-17 12:21 UTC, DarwinsBuddy commented on .vscode/launch.json
> +        // Example of attaching to local debug server
please do not commit comments in json :)

2022-12-17 12:21 UTC, DarwinsBuddy commented on .vscode/launch.json
> +        // Example of attaching to my production server
please do not commit comments in json :)

2022-12-17 12:21 UTC, DarwinsBuddy commented on .devcontainer/devcontainer.json
> +// See https://aka.ms/vscode-remote/devcontainer.json for format details.
please do not commit comments in json :)

2022-12-17 12:35 UTC, DarwinsBuddy commented
@TheRealVira I tried to contact you, but you make it really a challenge. :smile:  No email, no keybase, no nothing.

If you're interested furthermore on this project, either write me an email (christoph.spoerk@gmail.com) and/or create a keybase account for a secure channel: https://keybase.io/app

Have a nice weekend.
Cheers!

2022-12-17 12:41 UTC, TheRealVira commented
Hey @DarwinsBuddy I'll get back to you as soon as I can. For now, please check out my LinkedIn: 

https://at.linkedin.com/in/ruehrig-j

I'll aso implement the suggested changes - no problem :D I love to support local projects, especially if they have the capability to make a great impact. With WNSM I can really see how this integration could support people saving energy and money for "free".

2022-12-17 12:45 UTC, DarwinsBuddy commented
I found your profile already, though I am not having premium, thus I cannot send you a message. :grimacing:

2022-12-17 13:08 UTC, TheRealVira commented
Wtf since when do you need LinkedIn Premium for messages.. whatever, here is my e-mail address:

therealvira@gmail.com

I'll also update my GitHub profile Readme to display my e-mail address.

2022-12-22 12:00 UTC, TheRealVira commented
Anything else needed from my side? @DarwinsBuddy

2022-12-22 19:18 UTC, DarwinsBuddy commented
hi sry. much to do in the office the last weeks. I hope I'll get to it tomorrow 🤞🤞🤞

2022-12-30 09:19 UTC, merged